export const LOCALE_CHANGED = 'LOCALE_CHANGED';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_OUT = 'AUTH_USER_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';
export const UPDATE_USERS_SUCCESS  = 'UPDATE_USERS_SUCCESS';
export const SET_USERS_FILTER  = 'SET_USERS_FILTER';
export const RESET_USERS_FILTER = 'RESET_USERS_FILTER';

export const INVALIDATE_PLACES  = 'INVALIDATE_PLACES';
export const PLACES_CLEARED     = 'PLACES_CLEARED';
export const SET_PLACE_FILTER   = 'SET_PLACE_FILTER';
export const RESET_PLACE_FILTER = 'RESET_PLACE_FILTER';
export const GET_PLACES_REQUEST = 'GET_PLACES_REQUEST';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';
export const POST_PLACE_SUCCESS = 'POST_PLACE_SUCCESS';
export const POST_PLACE_FAILURE = 'POST_PLACE_FAILURE';
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const UPDATE_PLACE_FAILURE = 'UPDATE_PLACE_FAILURE';
export const DELETE_PLACES_SUCCESS = 'DELETE_PLACES_SUCCESS';
export const DELETE_PLACES_FAILURE = 'DELETE_PLACES_FAILURE';

export const ERROR_DISMISSED    = 'ERROR_DISMISSED';

export const INVALIDATE_EVENTS  = 'INVALIDATE_EVENTS';
export const CHANGE_EVENT_PAGE  = 'CHANGE_EVENT_PAGE';
export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILURE = 'POST_EVENT_FAILURE';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
export const SET_EVENT_FILTER   = 'SET_EVENT_FILTER';
export const RESET_EVENT_FILTER = 'RESET_EVENT_FILTER';

export const CHANGE_ARTICLE_PAGE  = 'CHANGE_ARTICLE_PAGE';
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE';

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE';
export const POST_PHOTO_SUCCESS = 'POST_PHOTO_SUCCESS';
export const POST_PHOTO_FAILURE = 'POST_PHOTO_FAILURE';

export const INVALIDATE_TAGS  = 'INVALIDATE_TAGS';
export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';
export const POST_TAG_SUCCESS = 'POST_TAG_SUCCESS';
export const POST_TAG_FAILURE = 'POST_TAG_FAILURE';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';
export const SET_TAG_FILTER   = 'SET_TAG_FILTER';
export const RESET_TAG_FILTER = 'RESET_TAG_FILTER';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';

export const SET_NOTIFICATION 		= 'SET_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';