export const LOCALE_CHANGED = 'LOCALE_CHANGED';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_OUT = 'AUTH_USER_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const PLACES_CLEARED = 'PLACES_CLEARED';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';
export const POST_PLACE_SUCCESS = 'POST_PLACE_SUCCESS';
export const POST_PLACE_FAILURE = 'POST_PLACE_FAILURE';

export const ERROR_DISMISSED = 'ERROR_DISMISSED';
export const ERROR_SAVING_PLACE = 'ERROR_SAVING_PLACE';

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILURE = 'POST_EVENT_FAILURE';

export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_FAILURE = 'POST_ARTICLE_FAILURE';

export const CHANGE_EVENT_PAGE = 'CHANGE_PAGE';

export const USERS_LOADED = 'USERS_LOADED';

//todo: unify action naming and use FETCH instead of loaded, ...